# Generated by Django 3.2 on 2021-05-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210508_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
